name: Update JDK 15
"on":
    schedule:
        - cron: 0 5 * * 1-5
    workflow_dispatch: {}
jobs:
    update:
        name: Update Buildpack Dependency
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/setup-go@v2
              with:
                go-version: "1.15"
            - name: Install update-buildpack-dependency
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                GO111MODULE=on go get -u -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/update-buildpack-dependency
            - name: Install yj
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing yj ${YJ_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  --output "${HOME}"/bin/yj \
                  "https://github.com/sclevine/yj/releases/download/v${YJ_VERSION}/yj-linux"

                chmod +x "${HOME}"/bin/yj
              env:
                YJ_VERSION: 5.0.0
            - uses: actions/checkout@v2
            - id: dependency
              uses: docker://ghcr.io/paketo-buildpacks/actions/bellsoft-liberica-dependency:main
              with:
                type: jdk
                version: "15"
            - id: buildpack
              name: Update Buildpack Dependency
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                OLD_VERSION=$(yj -tj < buildpack.toml | jq -r "
                  .metadata.dependencies[] |
                  select( .id == env.ID ) |
                  select( .version | test( env.VERSION_PATTERN ) ) |
                  .version")

                update-buildpack-dependency \
                  --buildpack-toml buildpack.toml \
                  --id "${ID}" \
                  --version-pattern "${VERSION_PATTERN}" \
                  --version "${VERSION}" \
                  --uri "${URI}" \
                  --sha256 "${SHA256}"

                git add buildpack.toml
                git checkout -- .

                echo "::set-output name=old-version::${OLD_VERSION}"
                echo "::set-output name=new-version::${VERSION}"
              env:
                ID: jdk
                SHA256: ${{ steps.dependency.outputs.sha256 }}
                URI: ${{ steps.dependency.outputs.uri }}
                VERSION: ${{ steps.dependency.outputs.version }}
                VERSION_PATTERN: 15\.[\d]+\.[\d]+
            - uses: peter-evans/create-pull-request@v3
              with:
                author: ${{ secrets.JAVA_GITHUB_USERNAME }} <${{ secrets.JAVA_GITHUB_USERNAME }}@users.noreply.github.com>
                body: Bumps `JDK 15` from `${{ steps.buildpack.outputs.old-version }}` to `${{ steps.buildpack.outputs.new-version }}`.
                branch: update/buildpack/jdk-15
                commit-message: |-
                    Bump JDK 15 from ${{ steps.buildpack.outputs.old-version }} to ${{ steps.buildpack.outputs.new-version }}

                    Bumps JDK 15 from ${{ steps.buildpack.outputs.old-version }} to ${{ steps.buildpack.outputs.new-version }}.
                delete-branch: true
                labels: semver:minor, type:dependency-upgrade
                signoff: true
                title: Bump JDK 15 from ${{ steps.buildpack.outputs.old-version }} to ${{ steps.buildpack.outputs.new-version }}
                token: ${{ secrets.JAVA_GITHUB_TOKEN }}
